# Generated by Django 4.1 on 2022-08-28 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='University',
            new_name='UniversityClasses',
        ),
    ]
